// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" --prefix-filecheck-ir-name TMP_

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O0
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s --check-prefix=CHECK-O2

#include <ptrcheck.h>

struct S {
    int *__counted_by(l) bp;
    int *bp2 __counted_by(l+1);
    int l;
};

// CHECK-O0-LABEL: @foo(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-O0-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 8
// CHECK-O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[TMP_TMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP6:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP13:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[TMP_TMP14:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP17:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP24:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP33:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[AGG_TEMP42:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP43:%.*]] = alloca [[STRUCT_S]], align 8
// CHECK-O0-NEXT:    [[AGG_TEMP58:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP59:%.*]] = alloca [[STRUCT_S]], align 8
// CHECK-O0-NEXT:    [[AGG_TEMP77:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP78:%.*]] = alloca [[STRUCT_S]], align 8
// CHECK-O0-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// CHECK-O0-NEXT:    [[ARRAYDECAY2:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER3:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY2]], i64 10
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY2]], ptr [[TMP3]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER3]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP1]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY2]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    br i1 true, label [[CONT:%.*]], label [[TRAP:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont:
// CHECK-O0-NEXT:    br i1 true, label [[CONT5:%.*]], label [[TRAP4:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap4:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont5:
// CHECK-O0-NEXT:    [[BP:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[BP]], align 8
// CHECK-O0-NEXT:    [[BP2:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP6]], ptr align 8 [[TMP_TMP1]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR7:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR8:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR7]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR9:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB10:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR9]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR11:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB12:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR11]], align 8
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR8]], ptr [[BP2]], align 8
// CHECK-O0-NEXT:    [[L:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    store i32 0, ptr [[L]], align 8
// CHECK-O0-NEXT:    [[ARRAYDECAY15:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER16:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY15]], i64 10
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY15]], ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER16]], ptr [[TMP7]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY15]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP10]], i64 1
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[TMP13]], ptr [[TMP14]], align 8
// CHECK-O0-NEXT:    [[TMP15:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP14]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP15]], align 8
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP13]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP16]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    [[ARRAYDECAY18:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER19:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY18]], i64 10
// CHECK-O0-NEXT:    [[TMP18:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY18]], ptr [[TMP18]], align 8
// CHECK-O0-NEXT:    [[TMP19:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER19]], ptr [[TMP19]], align 8
// CHECK-O0-NEXT:    [[TMP20:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP17]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY18]], ptr [[TMP20]], align 8
// CHECK-O0-NEXT:    br i1 true, label [[CONT21:%.*]], label [[TRAP20:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap20:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont21:
// CHECK-O0-NEXT:    br i1 true, label [[CONT23:%.*]], label [[TRAP22:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap22:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont23:
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP24]], ptr align 8 [[AGG_TEMP13]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR25:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR26:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR25]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR27:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB28:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR27]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR29:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP24]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB30:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR29]], align 8
// CHECK-O0-NEXT:    [[BP31:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR26]], ptr [[BP31]], align 8
// CHECK-O0-NEXT:    [[L32:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    store i32 8, ptr [[L32]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP33]], ptr align 8 [[AGG_TEMP17]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR34:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR35:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR34]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR36:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB37:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR36]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR38:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP33]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB39:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR38]], align 8
// CHECK-O0-NEXT:    [[BP240:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR35]], ptr [[BP240]], align 8
// CHECK-O0-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-O0-NEXT:    br label [[FOR_COND:%.*]]
// CHECK-O0:       for.cond:
// CHECK-O0-NEXT:    [[TMP21:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    [[L41:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[S]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP22:%.*]] = load i32, ptr [[L41]], align 8
// CHECK-O0-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP21]], [[TMP22]]
// CHECK-O0-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK-O0:       for.body:
// CHECK-O0-NEXT:    [[TMP23:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP43]], ptr align 8 [[S]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[L44:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP43]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP24:%.*]] = load i32, ptr [[L44]], align 8
// CHECK-O0-NEXT:    [[BP45:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP43]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP25:%.*]] = load ptr, ptr [[BP45]], align 8
// CHECK-O0-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP24]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP25]], i64 [[IDX_EXT]]
// CHECK-O0-NEXT:    [[TMP26:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[TMP25]], ptr [[TMP26]], align 8
// CHECK-O0-NEXT:    [[TMP27:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP27]], align 8
// CHECK-O0-NEXT:    [[TMP28:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP25]], ptr [[TMP28]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR46:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR47:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR46]], align 8
// CHECK-O0-NEXT:    [[TMP29:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP29]] to i64
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR47]], i64 [[IDXPROM]]
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR48:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB49:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR48]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR50:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP42]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB51:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR50]], align 8
// CHECK-O0-NEXT:    [[TMP30:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP31:%.*]] = icmp ule ptr [[TMP30]], [[WIDE_PTR_UB49]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP31]], label [[CONT53:%.*]], label [[TRAP52:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap52:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont53:
// CHECK-O0-NEXT:    [[TMP32:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP30]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP32]], label [[CONT55:%.*]], label [[TRAP54:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap54:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont55:
// CHECK-O0-NEXT:    [[TMP33:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB51]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP33]], label [[CONT57:%.*]], label [[TRAP56:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap56:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont57:
// CHECK-O0-NEXT:    store i32 [[TMP23]], ptr [[ARRAYIDX]], align 4
// CHECK-O0-NEXT:    br label [[FOR_INC:%.*]]
// CHECK-O0:       for.inc:
// CHECK-O0-NEXT:    [[TMP34:%.*]] = load i32, ptr [[I]], align 4
// CHECK-O0-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP34]], 1
// CHECK-O0-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-O0-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP5:![0-9]+]]
// CHECK-O0:       for.end:
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP59]], ptr align 8 [[S]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[L60:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP59]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP35:%.*]] = load i32, ptr [[L60]], align 8
// CHECK-O0-NEXT:    [[BP261:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP59]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP36:%.*]] = load ptr, ptr [[BP261]], align 8
// CHECK-O0-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP35]], 1
// CHECK-O0-NEXT:    [[IDX_EXT62:%.*]] = sext i32 [[ADD]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR63:%.*]] = getelementptr inbounds i32, ptr [[TMP36]], i64 [[IDX_EXT62]]
// CHECK-O0-NEXT:    [[TMP37:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP58]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[TMP36]], ptr [[TMP37]], align 8
// CHECK-O0-NEXT:    [[TMP38:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP58]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR63]], ptr [[TMP38]], align 8
// CHECK-O0-NEXT:    [[TMP39:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP58]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP36]], ptr [[TMP39]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR64:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP58]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR65:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR64]], align 8
// CHECK-O0-NEXT:    [[ARRAYIDX66:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR65]], i64 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR67:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP58]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB68:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR67]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR69:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP58]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB70:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR69]], align 8
// CHECK-O0-NEXT:    [[TMP40:%.*]] = getelementptr i32, ptr [[ARRAYIDX66]], i64 1, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP41:%.*]] = icmp ule ptr [[TMP40]], [[WIDE_PTR_UB68]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP41]], label [[CONT72:%.*]], label [[TRAP71:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap71:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont72:
// CHECK-O0-NEXT:    [[TMP42:%.*]] = icmp ule ptr [[ARRAYIDX66]], [[TMP40]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP42]], label [[CONT74:%.*]], label [[TRAP73:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap73:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont74:
// CHECK-O0-NEXT:    [[TMP43:%.*]] = icmp uge ptr [[ARRAYIDX66]], [[WIDE_PTR_LB70]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP43]], label [[CONT76:%.*]], label [[TRAP75:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap75:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont76:
// CHECK-O0-NEXT:    [[TMP44:%.*]] = load i32, ptr [[ARRAYIDX66]], align 4
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP78]], ptr align 8 [[S]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[L79:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP78]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP45:%.*]] = load i32, ptr [[L79]], align 8
// CHECK-O0-NEXT:    [[BP80:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP78]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP46:%.*]] = load ptr, ptr [[BP80]], align 8
// CHECK-O0-NEXT:    [[IDX_EXT81:%.*]] = sext i32 [[TMP45]] to i64
// CHECK-O0-NEXT:    [[ADD_PTR82:%.*]] = getelementptr inbounds i32, ptr [[TMP46]], i64 [[IDX_EXT81]]
// CHECK-O0-NEXT:    [[TMP47:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP77]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[TMP46]], ptr [[TMP47]], align 8
// CHECK-O0-NEXT:    [[TMP48:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP77]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[ADD_PTR82]], ptr [[TMP48]], align 8
// CHECK-O0-NEXT:    [[TMP49:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP77]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP46]], ptr [[TMP49]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR83:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP77]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR84:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR83]], align 8
// CHECK-O0-NEXT:    [[ARRAYIDX85:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR84]], i64 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR86:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP77]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB87:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR86]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR88:%.*]] = getelementptr inbounds %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP77]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB89:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR88]], align 8
// CHECK-O0-NEXT:    [[TMP50:%.*]] = getelementptr i32, ptr [[ARRAYIDX85]], i64 1, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP51:%.*]] = icmp ule ptr [[TMP50]], [[WIDE_PTR_UB87]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP51]], label [[CONT91:%.*]], label [[TRAP90:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap90:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont91:
// CHECK-O0-NEXT:    [[TMP52:%.*]] = icmp ule ptr [[ARRAYIDX85]], [[TMP50]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP52]], label [[CONT93:%.*]], label [[TRAP92:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap92:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont93:
// CHECK-O0-NEXT:    [[TMP53:%.*]] = icmp uge ptr [[ARRAYIDX85]], [[WIDE_PTR_LB89]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP53]], label [[CONT95:%.*]], label [[TRAP94:%.*]], {{!annotation ![0-9]+}}
// CHECK-O0:       trap94:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       cont95:
// CHECK-O0-NEXT:    [[TMP54:%.*]] = load i32, ptr [[ARRAYIDX85]], align 4
// CHECK-O0-NEXT:    [[ADD96:%.*]] = add nsw i32 [[TMP44]], [[TMP54]]
// CHECK-O0-NEXT:    ret i32 [[ADD96]]
//
// CHECK-O2-LABEL: @foo(
// CHECK-O2-NEXT:  trap:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int foo () {
    int arr[10];
    struct S s = {arr, arr, 0};
    s.bp = &arr[1];
    s.l = 8;
    s.bp2 = arr;
    // run-time check here

    for (int i = 0; i < s.l; ++i)
        s.bp[i] = i;

    return s.bp2[8] + s.bp[8]; // trap : oob s.bp[8]
}


