; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=arm64-apple-macosx -O3 -early-ifcvt-limit=0 -select-opti-loop-cycle-gain-threshold=2 -select-opti-loop-gradient-gain-threshold=10 -mcpu=apple-a7 -o - %s | FileCheck --check-prefix=DISABLED %s
; RUN: llc -mtriple=arm64-apple-macosx -O3 -early-ifcvt-limit=0 -select-opti-loop-cycle-gain-threshold=2 -select-opti-loop-gradient-gain-threshold=10 -mcpu=apple-m1 -o - %s | FileCheck --check-prefix=ENABLED %s
; RUN: llc -mtriple=arm64-apple-macosx -O3 -early-ifcvt-limit=0 -select-opti-loop-cycle-gain-threshold=2 -select-opti-loop-gradient-gain-threshold=10 -mcpu=apple-m2 -o - %s | FileCheck --check-prefix=ENABLED %s
; RUN: llc -mtriple=arm64-apple-macosx -O3 -early-ifcvt-limit=0 -select-opti-loop-cycle-gain-threshold=2 -select-opti-loop-gradient-gain-threshold=10 -mcpu=apple-m3 -o - %s | FileCheck --check-prefix=ENABLED %s
; RUN: llc -mtriple=arm64-apple-macosx -O3 -early-ifcvt-limit=0 -select-opti-loop-cycle-gain-threshold=2 -select-opti-loop-gradient-gain-threshold=10 -mcpu=apple-m4 -o - %s | FileCheck --check-prefix=ENABLED %s

define void @test_select_opt(ptr %dst, ptr %src, i64 %j.start, i64 %p, i64 %i.start) {
; DISABLED-LABEL: test_select_opt:
; DISABLED:       ; %bb.0: ; %entry
; DISABLED-NEXT:    add x8, x2, #1
; DISABLED-NEXT:  LBB0_1: ; %loop
; DISABLED-NEXT:    ; =>This Inner Loop Header: Depth=1
; DISABLED-NEXT:    ldr x9, [x1, x4, lsl #3]
; DISABLED-NEXT:    ldr x10, [x1, x2, lsl #3]
; DISABLED-NEXT:    cmp x9, x10
; DISABLED-NEXT:    cset w9, lo
; DISABLED-NEXT:    cinc x2, x2, lo
; DISABLED-NEXT:    sub x9, x4, x9
; DISABLED-NEXT:    str x2, [x0, x9, lsl #3]
; DISABLED-NEXT:    mov x4, x2
; DISABLED-NEXT:    subs x8, x8, #1
; DISABLED-NEXT:    b.ne LBB0_1
; DISABLED-NEXT:  ; %bb.2: ; %exit
; DISABLED-NEXT:    ret
;
; ENABLED-LABEL: test_select_opt:
; ENABLED:       ; %bb.0: ; %entry
; ENABLED-NEXT:    add x8, x2, #1
; ENABLED-NEXT:    b LBB0_2
; ENABLED-NEXT:  LBB0_1: ; %select.end
; ENABLED-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; ENABLED-NEXT:    str x2, [x0, x4, lsl #3]
; ENABLED-NEXT:    mov x4, x2
; ENABLED-NEXT:    subs x8, x8, #1
; ENABLED-NEXT:    b.eq LBB0_4
; ENABLED-NEXT:  LBB0_2: ; %loop
; ENABLED-NEXT:    ; =>This Inner Loop Header: Depth=1
; ENABLED-NEXT:    ldr x9, [x1, x4, lsl #3]
; ENABLED-NEXT:    ldr x10, [x1, x2, lsl #3]
; ENABLED-NEXT:    cmp x9, x10
; ENABLED-NEXT:    b.hs LBB0_1
; ENABLED-NEXT:  ; %bb.3: ; %select.true.sink
; ENABLED-NEXT:    ; in Loop: Header=BB0_2 Depth=1
; ENABLED-NEXT:    add x2, x2, #1
; ENABLED-NEXT:    sub x4, x4, #1
; ENABLED-NEXT:    b LBB0_1
; ENABLED-NEXT:  LBB0_4: ; %exit
; ENABLED-NEXT:    ret
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %j = phi i64 [ %j.start, %entry ], [ %j.next, %loop ]
  %i = phi i64 [ %i.start, %entry ], [ %j.next, %loop ]
  %gep.i = getelementptr inbounds ptr, ptr %src, i64 %i
  %l.i = load ptr, ptr %gep.i, align 8
  %gep.j = getelementptr inbounds ptr, ptr %src, i64 %j
  %l.j = load ptr, ptr %gep.j, align 8
  %cmp3 = icmp ult ptr %l.i, %l.j
  %dec = zext i1 %cmp3 to i64
  %dec.i = sext i1 %cmp3 to i64
  %j.next = add nsw i64 %j, %dec
  %i.next = add nsw i64 %i, %dec.i
  %gep.dst = getelementptr inbounds ptr, ptr %dst, i64 %i.next
  store i64 %j.next, ptr %gep.dst, align 8
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv, %j.start
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}
